#define NUMERO_VERSION_PROTOCOLE_RADIO_U8 ((uint8_t)1)
#define NUMERO_RESEAU_U8 ((uint8_t)1)
#define DEFAULT_ADDRESS_U8 ((uint8_t)0x69)

#define VERSION_MAJEURE_FIRMWARE_CA "00"
#define VERSION_MINEURE_FIRMWARE_CA "00"
#define VERSION_BUILD_FIRMWARE_CA   "01"